# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Menu',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.BinaryField()),
                ('description', models.TextField()),
                ('veg', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=4)),
            ],
        ),
    ]
