# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='food_menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='food_menu',
            name='veg',
        ),
    ]
