# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20161125_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_menu',
            name='description',
            field=models.TextField(default='Enter description here'),
        ),
        migrations.AddField(
            model_name='food_menu',
            name='veg',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=4),
        ),
    ]
